version: '3'
env:
  APP_ENV: dev
tasks:
  depsgen:
    dir: cmd/graphql-server/dependencies
    cmds:
      - wire
  gqlgen:
    dir: cmd/graphql-server
    cmds:
      - echo 'Generating GraphQL Schema'
      - go run github.com/99designs/gqlgen generate
      - echo 'Generated Schema. Please check ./cmd/go-graphql-starter/graph folder for any errors.'
  migratedb:
    env:
      DATABASE_URL: '{{.DATABASE_URL | default "pgx://test:test@localhost:5435/notesdb"}}'
    cmds:
      - migrate -source file://migrations -database $DATABASE_URL  up
  run-graphql-server:
    dir: cmd/graphql-server
    cmds:
      - go build -o graphql-server
      - PORT=7777 ./graphql-server -configpath ./config/dev/config.yaml
  dockerize:
    cmds:
      - docker build -t dockerhub.com/go-graphql-starter/graphql-server:latest --build-arg ENV=stage -f cmd/graphql-server/_docker/Dockerfile .
  runtests:
    cmds:
      - (rm /tmp/unit_coverage.out || echo "Deleted Old files")
      - go test -mod=mod -v  -coverprofile  /tmp/unit_coverage.out ./...
  setupdev:
    cmds:
      - echo "Installing Wire for Compile Time Dependency Injection."
      - go install github.com/google/wire/cmd/wire@latest
  newmigration:
    cmds:
      - migrate create -ext sql -dir db/migrations -seq